name: Panamax

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Panamax Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: registry.fh.gov.cn
          # Docker repository to tag the image with
          repository: jianglibo/panamax
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          # tags: {{ $GITHUB_REF}}
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          # tag_with_sha: # optional
          # Path to the build context
          path: ./panamax
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          # dockerfile: # optional
          # Sets the target stage to build
          # target: # optional
          # Always attempt to pull a newer version of the image
          # always_pull: # optional
          # Comma-delimited list of build-time variables
          # build_args: # optional
          # Comma-delimited list of images to consider as cache sources
          # cache_froms: # optional
          # Comma-delimited list of labels to add to the built image
          # labels: # optional
          # Adds labels with git repository information to the built image
          # add_git_labels: # optional
          # Whether to push the image
          push: true
